name: Go Checks

on: [push]

jobs:
    gobuild:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.0
            - uses: actions/checkout@v4
            - name: go build
              run: go build -v ./...

    gotest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.0
            - uses: actions/checkout@v4
            - name: go build
              run: go test -v ./...

    golangci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.23.0
            - uses: actions/checkout@v4
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v5
              with:
                  version: latest
                  args: --skip-files "(.+)_test.go"
